services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongodb-network

networks:
  mongodb-network:
    driver: bridge
