services:
  elasticsearch:
    image: elasticsearch:8.18.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false

    volumes:
      - ./data:/usr/share/elasticsearch/data  # 数据目录
      - ./logs:/usr/share/elasticsearch/logs # 日志目录
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic-net

  kibana:
    image: kibana:8.18.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic-net

networks:
  elastic-net:
    driver: bridge

