services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ../.env
    environment:
      - TZ=Asia/Shanghai
    command:
      - sh
      - -c
      - exec redis-server /usr/local/etc/redis/redis.conf --requirepass "$$REDIS_PASSWORD"
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
